<a href="https://colab.research.google.com/github/ereny123/Multitasking-MThesis-2024/blob/main/Pytorch_NET_Multitasking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy

In [38]:
#create a model class
class Model(nn.Module):
  #Input (Tasks) random array of 9 units
  def __init__(self, in_tasks=9, in_stim=3, hidden= 100, output=9, bias_weight=-2):
    super().__init__()

    #Set Parameters
    self.bias_weight = bias_weight   # default bias weight

    self.task_hidden=nn.Linear(in_tasks, hidden)    #input layer(tasks) --> hidden layer
    self.stim_hidden=nn.Linear(in_stim, hidden)    #input layer(stimuls) --> hidden layer
    self.hidden_out=nn.Linear(hidden, output)       #hidden layer --> output layer

    self.task_hidden.weight=nn.Parameter(torch.FloatTensor(hidden, in_tasks).uniform_(-0.1, 0.1))   #input(tasks)-->hidden  weight
    self.stim_hidden.weight=nn.Parameter(torch.FloatTensor(hidden, in_stim).uniform_(-0.1, 0.1))    #input(stimulus) -->hidden weight
    self.hidden_out.weight=nn.Parameter(torch.FloatTensor(output, hidden).uniform_(-0.1, 0.1))      #hidden-->output  weight

    self.task_hidden.bias=nn.Parameter(torch.ones(hidden) * bias_weight)                         #hidden layer bias
    self.hidden_out.bias=nn.Parameter(torch.ones(output) * bias_weight)                    #output layer bias

  def forward(self, taskData, stimulusData):
    #h_act=torch.matmul(self.fc1.weight, taskData)+ self.fc1.bias   #hidden layer activation
    #h_act= F.tanh(self.h_act)
    #out_act=torch.matmul(self.fc2.weight, h_act) + self.fc2.bias    #output layer activation

    h_act=torch.sigmoid(self.task_hidden(taskData)+self.stim_hidden(stimulusData))
    out_act= self.hidden_out(h_act)

    return h_act, out_act




In [39]:
#Pick a manual seed for randomization for the input values
#torch.manual_seed(1729)
#tasks= torch.rand(1,9)
#tasks


#create an instance for Model
model = Model()
print(model)


Model(
  (task_hidden): Linear(in_features=9, out_features=100, bias=True)
  (stim_hidden): Linear(in_features=3, out_features=100, bias=True)
  (hidden_out): Linear(in_features=100, out_features=9, bias=True)
)


In [40]:
X = numpy.array([1, 2, 3 , 4, 5, 6, 7, 8, 9])
taskData = torch.from_numpy(X)
taskData=taskData.to(torch.float32)

Z=numpy.array([0,1,1])
stimulusData= torch.from_numpy(Z)
stimulusData=stimulusData.to(torch.float32)

print(taskData)
print(stimulusData)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0., 1., 1.])


In [41]:
model(taskData, stimulusData)

(tensor([0.2013, 0.0706, 0.1204, 0.2274, 0.3518, 0.1996, 0.1138, 0.0780, 0.0681,
         0.1455, 0.1853, 0.5240, 0.0156, 0.1727, 0.0402, 0.3577, 0.3332, 0.0785,
         0.1337, 0.2777, 0.0692, 0.0727, 0.1810, 0.1608, 0.1547, 0.1369, 0.0488,
         0.0837, 0.0316, 0.2525, 0.1218, 0.0714, 0.0471, 0.0968, 0.1973, 0.0692,
         0.2253, 0.2347, 0.1048, 0.0757, 0.0516, 0.1154, 0.1139, 0.4133, 0.1342,
         0.0218, 0.0297, 0.0338, 0.0708, 0.2750, 0.0310, 0.0421, 0.1989, 0.2773,
         0.0527, 0.1423, 0.1070, 0.2343, 0.5497, 0.0381, 0.3139, 0.4839, 0.1115,
         0.0768, 0.0496, 0.0420, 0.1768, 0.1300, 0.2744, 0.1465, 0.0958, 0.0300,
         0.2415, 0.1761, 0.1848, 0.1257, 0.0327, 0.2192, 0.4601, 0.2853, 0.1510,
         0.0844, 0.1815, 0.3252, 0.0430, 0.0247, 0.0521, 0.2898, 0.0303, 0.0178,
         0.0675, 0.1282, 0.1948, 0.1016, 0.0772, 0.1315, 0.4355, 0.3498, 0.2851,
         0.0834], grad_fn=<SigmoidBackward0>),
 tensor([-1.9042, -1.9486, -2.2325, -1.9064, -2.0178, -1.9636,