<a href="https://colab.research.google.com/github/ereny123/Multitasking-MThesis-2024/blob/main/Pytorch_NET_Multitasking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy

In [ ]:
#create a model class
class Model(nn.Module):
  #Input (Tasks) random array of 9 units
  def __init__(self, in_tasks=9, in_stim=3, hidden= 100, output=9, bias_weight=-2):
    super().__init__()

    #Set Parameters
    self.bias_weight = bias_weight   # default bias weight

    self.task_hidden=nn.Linear(in_tasks, hidden)    #input layer(tasks) --> hidden layer
    self.stim_hidden=nn.Linear(in_stim, hidden)     #input layer(stimuls) --> hidden layer
    self.task_out=nn.Linear(in_tasks, output)       #Input Layer(tasks) --> output layer
    self.hidden_out=nn.Linear(hidden, output)       #hidden layer --> output layer

    self.task_hidden.weight=nn.Parameter(torch.FloatTensor(hidden, in_tasks).uniform_(-0.1, 0.1))   #input(tasks)-->hidden  weight
    self.task_out.weight=nn.Parameter(torch.FloatTensor(output, in_tasks).uniform_(-0.1, 0.1))      #input(task) --> output weight
    self.stim_hidden.weight=nn.Parameter(torch.FloatTensor(hidden, in_stim).uniform_(-0.1, 0.1))    #input(stimulus) -->hidden weight
    self.hidden_out.weight=nn.Parameter(torch.FloatTensor(output, hidden).uniform_(-0.1, 0.1))      #hidden-->output  weight

    self.task_hidden.bias=nn.Parameter(torch.ones(hidden) * bias_weight)                         #hidden layer bias
    self.hidden_out.bias=nn.Parameter(torch.ones(output) * bias_weight)                    #output layer bias

  def forward(self, taskData, stimulusData):
    h_act=torch.sigmoid(self.task_hidden(taskData)+self.stim_hidden(stimulusData))   #hidden layer activation
    out_act= torch.sigmoid(self.hidden_out(h_act))   #output layer activation

    return h_act, out_act




In [ ]:
#create an instance for Model
model = Model()
print(model)


Model(
  (task_hidden): Linear(in_features=9, out_features=100, bias=True)
  (stim_hidden): Linear(in_features=3, out_features=100, bias=True)
  (task_out): Linear(in_features=9, out_features=9, bias=True)
  (hidden_out): Linear(in_features=100, out_features=9, bias=True)
)


In [ ]:
#Pick a manual seed for randomization for the input values
torch.manual_seed(3407)
taskData= torch.rand(1,9)
print(taskData)


Z=numpy.array([0,1,1])
stimulusData= torch.from_numpy(Z)
stimulusData=stimulusData.to(torch.float32)
print(stimulusData)

tensor([[0.7590, 0.7293, 0.1906, 0.8723, 0.2060, 0.3310, 0.6429, 0.4788, 0.7661]])
tensor([0., 1., 1.])


In [ ]:
model(taskData, stimulusData)

(tensor([[0.0862, 0.1171, 0.1410, 0.0861, 0.1399, 0.0840, 0.1265, 0.1155, 0.0744,
          0.1049, 0.0920, 0.1608, 0.0778, 0.1422, 0.1325, 0.1381, 0.1612, 0.0836,
          0.0922, 0.1392, 0.0937, 0.1945, 0.1774, 0.1130, 0.0858, 0.1488, 0.0832,
          0.1408, 0.1556, 0.2220, 0.2072, 0.1163, 0.1546, 0.1869, 0.0735, 0.1517,
          0.0713, 0.1284, 0.1302, 0.1837, 0.1523, 0.1527, 0.1731, 0.2174, 0.1928,
          0.1123, 0.0881, 0.1725, 0.1515, 0.1420, 0.1778, 0.1449, 0.1657, 0.1012,
          0.1389, 0.1400, 0.1711, 0.0962, 0.0926, 0.2070, 0.0760, 0.0729, 0.2068,
          0.1004, 0.0818, 0.0680, 0.0786, 0.1785, 0.0892, 0.1838, 0.1858, 0.1832,
          0.1124, 0.0827, 0.1746, 0.1080, 0.1195, 0.1474, 0.1403, 0.1043, 0.0967,
          0.0867, 0.1629, 0.1483, 0.1052, 0.1209, 0.1014, 0.1569, 0.0879, 0.1065,
          0.1387, 0.0656, 0.0992, 0.1274, 0.0926, 0.1468, 0.0850, 0.1088, 0.1111,
          0.0668]], grad_fn=<SigmoidBackward0>),
 tensor([[0.1385, 0.1203, 0.1115, 0.1158, 0.1252,